### ISSUE TITLE
GIT LFS Issue

### ISSUE THREAD

**Issue by nabilblk** [miho120/ambari-airflow-mpack#2]
Hi , 

I have a git lfs issue with your repository : 

```
[root@sandbox-hdp ~]# git lfs clone https://github.com/miho120/ambari-airflow-mpack
Cloning into 'ambari-airflow-mpack'...
remote: Counting objects: 130, done.
remote: Total 130 (delta 0), reused 0 (delta 0), pack-reused 130
Receiving objects: 100% (130/130), 573.38 KiB | 503.00 KiB/s, done.
Resolving deltas: 100% (45/45), done.
Checking connectivity... done.
Git LFS: (0 of 2 files) 0 B / 250.84 MB
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/miho120/ambari-airflow-mpack.git/info/lfs'
```

**Comment by miho120** [comment]
Hi @nabilblk ,
I've changed way of installing airflow and now no needs to use git lfs. Git lfs has been disabled for this repository. I suppose, won't be problems anymore.
Also I've added controlling of airflow scheduler and worker to mpack and now you can install (to multiple instances) and control: airflow webserver, scheduler and workers.

**Comment by nabilblk** [comment]
Thanks will test it tomorrow

**Comment by nabilblk** [comment]
the lfs problem is still there : 

```
[root@sandbox-hdp ~]# git clone https://github.com/eachsaj/ambari-airflow-mpack
Cloning into 'ambari-airflow-mpack'...
remote: Counting objects: 130, done.
remote: Total 130 (delta 0), reused 0 (delta 0), pack-reused 130
Receiving objects: 100% (130/130), 573.38 KiB | 346.00 KiB/s, done.
Resolving deltas: 100% (45/45), done.
Checking connectivity... done.
Downloading airflow-service-mpack.tar.gz (113 MB)
Error downloading object: airflow-service-mpack.tar.gz (046d0dc): Smudge error: Error downloading airflow-service-mpack.tar.gz (046d0dcae857dbc7c655ac79a42d05415abe0156366b72d05da1367da63a1b3f): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Errors logged to /root/ambari-airflow-mpack/.git/lfs/objects/logs/20180208T045545.99656145.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: airflow-service-mpack.tar.gz: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by miho120** [comment]
I've just checked from few different servers (where repo had never been cloned from git) and haven't met the issue.

Try to remove previous data: `rm -Rf /root/ambari-airflow-mpack/`

`[root@monkey 111]# git clone https://github.com/eachsaj/ambari-airflow-mpack
Initialized empty Git repository in /root/111/ambari-airflow-mpack/.git/
remote: Counting objects: 130, done.
remote: Total 130 (delta 0), reused 0 (delta 0), pack-reused 130
Receiving objects: 100% (130/130), 573.38 KiB | 376 KiB/s, done.
Resolving deltas: 100% (45/45), done.
[root@monkey 111]# ls -la
total 12
drwxr-xr-x   3 root root 4096 Mar  8 17:35 .
dr-xr-x---. 16 root root 4096 Mar  8 17:35 ..
drwxr-xr-x   5 root root 4096 Mar  8 17:35 ambari-airflow-mpack
[root@monkey 111]# ls -la ambari-airflow-mpack/
total 44
drwxr-xr-x 5 root root  4096 Mar  8 17:35 .
drwxr-xr-x 3 root root  4096 Mar  8 17:35 ..
drwxr-xr-x 5 root root  4096 Mar  8 17:35 airflow-service-mpack
-rw-r--r-- 1 root root   134 Mar  8 17:35 airflow-service-mpack.tar.gz
drwxr-xr-x 8 root root  4096 Mar  8 17:35 .git
-rw-r--r-- 1 root root   188 Mar  8 17:35 .gitattributes
-rw-r--r-- 1 root root 11357 Mar  8 17:35 LICENSE
-rw-r--r-- 1 root root  1601 Mar  8 17:35 README.md
drwxr-xr-x 2 root root  4096 Mar  8 17:35 Screenshots
[root@monkey 111]# `

**Comment by nabilblk** [comment]
That's fine ,  that was my fault i retest with an another repository `https://github.com/eachsaj/ambari-airflow-mpack`. 

Thanks for this great mpack .
