### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by technology20nn** [miho120/ambari-airflow-mpack#3]
Hi!
Im using ambari version 2.6.1.3  (Deploy HDP 2.6.4  hortonwork).
I download and install airflow mpack success.
But when i add service airflow on ambari it has error on action install.
It show message:

> Caught an exception while executing custom service command: <class 'ambari_agent.AgentException.AgentException'>: 'Script /var/lib/ambari-agent/cache/common-services/AIRFLOW/1.9.0/package/scripts/airflow_worker_control.py does not exist'; 'Script /var/lib/ambari-agent/cache/common-services/AIRFLOW/1.9.0/package/scripts/airflow_worker_control.py does not exist'

I don't known why script package not exist on ambari-agent. Please check with version ambari you run ok? 
Many Thanks!

**Comment by miho120** [comment]
Hi.
Should be any problem with this version.

Have you restarted ambari-server after installation?
Please check if these scripts exist on ambari-server host (/var/lib/ambari-server/resources/mpacks/airflow-ambari-mpack-1.3.6/common-services/AIRFLOW/1.9.0/package/scripts/)
Or try to reinstall mpak (--uninstall-mpack=airflow-ambari-mpack and then install mpack againg), then restart ambari-server and all agents.

**Comment by miho120** [comment]
The mpack adjusted to HDP 3.0. Long time no answer. Closing the issue.
