### ISSUE TITLE
error regarding python-pip 

### ISSUE THREAD

**Issue by sai9849** [miho120/ambari-airflow-mpack#4]
trying to use the master pack and it went smooth and while installing it throws following exception

raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/usr/bin/yum -d 0 -e 0 -y install python-pip' returned 1. Error: Nothing to do

we do not have yum install python-pip so i got from get-pip.py file and then installed in my node but still it throws the above error. 

could you please help me to fix the issue to bypass that error and also i am using virtual environments i did not get where this file located AIRFLOW_HOME/airflow_control.sh

**Comment by miho120** [comment]
Hi @sai9849.
You could modify mpack archive `airflow-service-mpack/common-services/AIRFLOW/1.9.0/metainfo.xml`, just delete line `<package><name>python-pip</name></package>`. 
Then reinstall mpack:
> ambari-server uninstall-mpack --mpack-name=airflow-ambari-mpack
> ambari-server install-mpack --mpack=airflow-service-mpack.tar.gz
> ambari-server restart

By default airflow_control.sh located here `/usr/local/airflow/airflow_venv/airflow_control.sh`

**Comment by miho120** [comment]
Not a regular case. Special environment. Long time no answer. Closing the issue.
