### ISSUE TITLE
ldap

### ISSUE THREAD

**Issue by ururu-fy** [miho120/ambari-airflow-mpack#5]
Hi.
When i added into "Custom airflow-webserver-site" preference, it is not implemented.
I need to add auth_backend_web=airflow.contrib.auth.backends.ldap_auth
But in airflow.cfg option din't appear and airflow didn't start.

**Comment by ururu-fy** [comment]
I guess it problem because need to put two same option together in different block.
[api]
auth_backend = airflow.api.auth.backend.default

[webserver]
authenticate = True
auth_backend = airflow.contrib.auth.backends.ldap_auth

**Comment by miho120** [comment]
Hi @ururu-fy.
Thanks for informing.
Support of custom configs has been added in commit 92dd09b407bea97af792231b6dd3c3c287112d3b.

**Comment by ururu-fy** [comment]
![image](https://user-images.githubusercontent.com/31213315/40661814-608bf712-635d-11e8-8332-989e7570502d.png)
![image](https://user-images.githubusercontent.com/31213315/40661828-673bac24-635d-11e8-825e-42837999745e.png)

**Comment by ururu-fy** [comment]
Sorry, wrong option's name. Everything is OK. Thanks!

**Comment by ururu-fy** [comment]
Done.
