### ISSUE TITLE
pip repo path

### ISSUE THREAD

**Issue by ururu-fy** [miho120/ambari-airflow-mpack#7]
I can't to install package from public repo because host have no internet access. I must install python package from internal repo only.  So could you please  add option where i can add path to repo during installation?
For example:
 pip install airflow --index-url https://link --trusted-host host

**Comment by miho120** [comment]
Hi @ururu-fy.
Thanks for informing.
Possibility to add pip arguments has been added in commit 92dd09b407bea97af792231b6dd3c3c287112d3b.
When you're installing airflow mpack and seeing service configuration form, go to "Advanced airflow-env" - "Advanced pip installation parameters"

E.g.:
![image](https://user-images.githubusercontent.com/4667951/40659061-72d1dd0c-634d-11e8-8e53-95f40bff8781.png)

**Comment by ururu-fy** [comment]
done

**Comment by miho120** [comment]
Have you tried reinstall airflow service in ambari?

**Comment by miho120** [comment]
Could you also send a screenshot of section configuration during installation process?

**Comment by ururu-fy** [comment]
I was  upgrade mpack only.

**Comment by ururu-fy** [comment]
Oh. sorry... i understand, option will appear into installation wizard. I will make new install on Dev cluster and will report you.

**Comment by ururu-fy** [comment]
Everything work fine, thanks!
