### ISSUE TITLE
local worker

### ISSUE THREAD

**Issue by ururu-fy** [miho120/ambari-airflow-mpack#8]
Ambari send alert message when have no Airflow Worker
But i don't want it, i run airflow as local executor mode.
![image](https://user-images.githubusercontent.com/31213315/40546934-3e50d4c8-6039-11e8-8316-c4fe81b32034.png)

**Comment by miho120** [comment]
Hi @ururu-fy.
Thanks for informing.
Requirement to have at least 1 worker has been changed in commit 92dd09b. Now Ambari shouldn't send alert message when you select no Airflow Worker.

**Comment by ururu-fy** [comment]
done
